# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: ogiorgis@logilab.fr
author_name: logilab
has_binder: false
has_settings: false
kind: server
labextension_name: jupyterlab-onyxia-composer
project_short_description: A JupyterLab extension for generate onyxia app
python_name: jupyterlab_onyxia_composer
repository: ''
test: false

